//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MetroModel.GraphServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GraphServiceSoap", Namespace="http://andreysergeev.org/graphservice")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebServiceResult))]
    public partial class GraphService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetConnectedGraphVertexDeletingSequenceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GraphService() {
            this.Url = global::MetroModel.Properties.Settings.Default.MetroModel_Implementation_GraphServiceReference_GraphService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetConnectedGraphVertexDeletingSequenceCompletedEventHandler GetConnectedGraphVertexDeletingSequenceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://andreysergeev.org/graphservice/GetConnectedGraphVertexDeletingSequence", RequestNamespace="http://andreysergeev.org/graphservice", ResponseNamespace="http://andreysergeev.org/graphservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetConnectedGraphVertexDeletingSequenceResult GetConnectedGraphVertexDeletingSequence(string inputXml) {
            object[] results = this.Invoke("GetConnectedGraphVertexDeletingSequence", new object[] {
                        inputXml});
            return ((GetConnectedGraphVertexDeletingSequenceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetConnectedGraphVertexDeletingSequenceAsync(string inputXml) {
            this.GetConnectedGraphVertexDeletingSequenceAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void GetConnectedGraphVertexDeletingSequenceAsync(string inputXml, object userState) {
            if ((this.GetConnectedGraphVertexDeletingSequenceOperationCompleted == null)) {
                this.GetConnectedGraphVertexDeletingSequenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConnectedGraphVertexDeletingSequenceOperationCompleted);
            }
            this.InvokeAsync("GetConnectedGraphVertexDeletingSequence", new object[] {
                        inputXml}, this.GetConnectedGraphVertexDeletingSequenceOperationCompleted, userState);
        }
        
        private void OnGetConnectedGraphVertexDeletingSequenceOperationCompleted(object arg) {
            if ((this.GetConnectedGraphVertexDeletingSequenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConnectedGraphVertexDeletingSequenceCompleted(this, new GetConnectedGraphVertexDeletingSequenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://andreysergeev.org/graphservice")]
    public partial class GetConnectedGraphVertexDeletingSequenceResult : WebServiceResult {
        
        private int[] sequenceField;
        
        /// <remarks/>
        public int[] Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetConnectedGraphVertexDeletingSequenceResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://andreysergeev.org/graphservice")]
    public partial class WebServiceResult {
        
        private bool successField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetConnectedGraphVertexDeletingSequenceCompletedEventHandler(object sender, GetConnectedGraphVertexDeletingSequenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConnectedGraphVertexDeletingSequenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConnectedGraphVertexDeletingSequenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetConnectedGraphVertexDeletingSequenceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetConnectedGraphVertexDeletingSequenceResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591